### ISSUE TITLE
html file very slow to open

### ISSUE THREAD

**Issue by djouallah** [uber/kepler.gl#468] opened 2019-04-05 23:21 UTC
I just tried the export to html, fantastic feature, only problem, when I click on the exported html file, it takes nearly 10 seconds to open

windows 10, chrome

**Comment by heshan0131** [comment] 2019-04-08 21:06
How big is your data and how big is your html? It might be because the entire data is serialized as a json object, which takes a while to read.

**Comment by djouallah** [comment] 2019-04-09 02:29
I just tried with California Earthquakes and it takes 15 seconds to load the html, is this expected ?, I use leaflet for other projects and it is way faster even with 70K points ?

**Comment by chrisirhc** [comment] 2019-04-09 03:45
@djouallah to clarify, do you only see this on the exported HTML or do you experience a similar issue on kepler.gl website?

**Comment by djouallah** [comment] 2019-04-09 03:59
no, the kepler.gl is very smooth !!!

**Comment by heshan0131** [comment] 2019-04-09 08:27
What's your chrome version?I have to test with a windows, It opens for me instantly on MacOS and chrome

**Comment by djouallah** [comment] 2019-04-09 12:07
Version 73.0.3683.75 (Official Build) (64-bit) windows 10

**Comment by heshan0131** [comment] 2019-04-09 17:10
I have Version 73.0.3683.86 (Official Build) (64-bit) so yours should be fine.
The error log is always there, same as the app. 
The only difference here is Windows vs Mac

**Comment by stevenroussey-desiclabs** [comment] 2019-04-10 01:38
I've noticed a huge difference between kepler.gl 0.2.4 (fast) and 1.0.0-0 (slow -- chrome will ask if I want to kill the process)

**Comment by stevenroussey-desiclabs** [comment] 2019-04-10 02:43
I was mistaken. I ran profiling and it was my code. It appears to have an issue loading on 1.0 if you don't have the mouse over kepler the data won't show. but the big delay i experienced was in my code not a difference in version #s.

**Comment by macrigiuseppe** [comment] 2019-04-26 18:17
@macrigiuseppe try to reproduce the issue on windows

**Comment by macrigiuseppe** [comment] 2019-04-30 23:56
@djouallah I found the root cause of the issue, some of the asset header links are timing out and blocking the rest of the browser flow.
I provided a fix in #488 
As soon as the branch will be merged i will publish a new version of our demo site with the enahnced export functionality

**Closed** 2019-05-01 22:20 UTC

**Comment by djouallah** [comment] 2019-05-07 00:25
@macrigiuseppe  great works, it is very fast now, thank you
